server:
  port: 8236

spring:
  redis:
    host: kk.hb520.site
    port: 2184


  application:
    name: "memberCenter"
  cloud:
    zookeeper:
      connect-string: kk.hb520.site:2181
      discovery:
        instance-host: 192.168.1.9
        instance-port: 8236
logging:
  level:
    sql: debug